#spring.application.name=springboot-developer
spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  datasource: # DB 정보 추가
    url: jdbc:h2:mem:testdb
  h2: # H2 콘솔 활성화
    console:
      enabled: true